# Kotlin configuration
kotlin.code.style=official

# Gradle options
org.gradle.parallel=true

group=eu.europa.ec.eudi
version=0.2.2

# Maven publishing properties
SONATYPE_HOST=CENTRAL_PORTAL
SONATYPE_AUTOMATIC_RELEASE=false
RELEASE_SIGNING_ENABLED=true

POM_NAME=EUDI ABCA Keycloak extension
POM_DESCRIPTION=Attestation-based client authentication support for Keycloack
POM_URL=https://github.com/eu-digital-identity-wallet/keycloak-client-attestation-auth-ext

POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt

POM_SCM_URL=https://github.com/eu-digital-identity-wallet/keycloak-client-attestation-auth-ext
POM_SCM_CONNECTION=scm:git:git@github.com:eu-digital-identity-wallet/keycloak-client-attestation-auth-ext.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com:eu-digital-identity-wallet/keycloak-client-attestation-auth-ext.git

POM_ISSUE_SYSTEM=github
POM_ISSUE_URL=https://github.com/eu-digital-identity-wallet/keycloak-client-attestation-auth-ext/issues

POM_DEVELOPER_URL=https://github.com/eu-digital-identity-wallet
